# Generated by Django 3.1.4 on 2022-03-16 13:33

import ckeditor.fields
from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apply_job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=100, null=True)),
                ('contact', phone_field.models.PhoneField(help_text='Contact number', max_length=31, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('position_applying_for', models.CharField(default='', max_length=100)),
                ('skills', models.TextField(blank=True, null=True)),
                ('experience', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('Resume', models.FileField(upload_to='pdfs/')),
                ('source', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('specify', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlockChain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(default='', max_length=100)),
                ('service_para', ckeditor.fields.RichTextField(default='')),
                ('service_date', models.DateField(auto_now=True)),
                ('service_slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_image', models.ImageField(default='', upload_to='media')),
                ('blog_title', models.CharField(default='', max_length=80)),
                ('blog_para', ckeditor.fields.RichTextField(default='')),
                ('blog_date', models.DateField(auto_now=True)),
                ('blog_slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('opening', models.IntegerField()),
                ('experience_in_years', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('join_duration_days', models.IntegerField()),
                ('job_description', models.TextField(blank=True, null=True)),
                ('Available', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(default='', max_length=50)),
                ('contact_email', models.EmailField(default='', max_length=100)),
                ('contact_subj', models.CharField(default='', max_length=200)),
                ('contact_msg', models.TextField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=50)),
                ('user_email', models.EmailField(default='', max_length=100)),
                ('subj', models.CharField(default='', max_length=200)),
                ('contact_msg', models.TextField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=100, null=True)),
                ('contact', phone_field.models.PhoneField(help_text='Contact number', max_length=31, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('source', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('specify', models.TextField(blank=True, default='', null=True)),
                ('notes', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(default='', max_length=100)),
                ('product_category', models.CharField(default='', max_length=80)),
                ('product_img', models.ImageField(blank=True, default='', null=True, upload_to='media')),
                ('product_para', ckeditor.fields.RichTextField(default='')),
                ('product_date', models.DateField(auto_now=True)),
                ('product_slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_title', models.CharField(default='', max_length=100)),
                ('resource_para', ckeditor.fields.RichTextField(default='')),
                ('resource_img', models.ImageField(blank=True, default='', null=True, upload_to='media')),
                ('resource_date', models.DateField(auto_now=True)),
                ('resource_slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(default='', max_length=100)),
                ('service_category', models.CharField(default='', max_length=80)),
                ('service_img', models.ImageField(blank=True, default='', null=True, upload_to='media')),
                ('service_para', ckeditor.fields.RichTextField(default='')),
                ('service_date', models.DateField(auto_now=True)),
                ('service_slug', models.SlugField(blank=True)),
            ],
        ),
    ]
