# Generated by Django 3.1.4 on 2022-03-22 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Infograins', '0002_mtags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtags',
            name='Block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BlockChain', to='Infograins.blockchain'),
        ),
    ]
