# Generated by Django 3.1.4 on 2022-04-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Infograins', '0009_auto_20220419_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtag',
            name='service_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
