# Generated by Django 3.1.4 on 2022-05-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Infograins', '0011_productschema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productschema',
            name='rating_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
