# Generated by Django 3.1.4 on 2022-05-27 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Infograins', '0012_auto_20220516_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fork_Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fork_name', models.CharField(default='', max_length=100)),
                ('fork_img', models.ImageField(blank=True, default='', null=True, upload_to='media')),
                ('fork_block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Infograins.fork_title')),
            ],
        ),
    ]
