# Generated by Django 3.1.4 on 2022-05-27 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Infograins', '0013_fork_fork_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fork',
            name='fork_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Infograins.fork_title'),
        ),
    ]
