# Generated by Django 3.1.4 on 2022-05-27 12:13

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('Infograins', '0014_auto_20220527_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fork_Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, default='', max_length=100, null=True)),
                ('contact', phone_field.models.PhoneField(help_text='Contact number', max_length=31, null=True)),
                ('country', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
