# Generated by Django 3.1.4 on 2022-05-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Infograins', '0016_auto_20220527_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='fork_form',
            name='demo_for',
            field=models.CharField(default='', max_length=100),
        ),
    ]
