# Generated by Django 3.1.4 on 2022-05-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Infograins', '0018_fork_form_skype_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fork_title',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
