# Generated by Django 3.1.4 on 2022-06-14 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Infograins', '0019_fork_title_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_value', models.FloatField(blank=True, null=True)),
                ('rating_count', models.IntegerField(blank=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_schema', to='Infograins.service')),
            ],
        ),
        migrations.CreateModel(
            name='BlockchainSchemas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_value', models.FloatField(blank=True, null=True)),
                ('rating_count', models.IntegerField(blank=True, null=True)),
                ('blockchain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_schema', to='Infograins.blockchain')),
            ],
        ),
    ]
