# Generated by Django 4.0.6 on 2022-07-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Infograins', '0021_product_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_img',
            new_name='product_image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_para',
            new_name='product_paragraph',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_category',
            new_name='productname',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_title',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.TextField(verbose_name=''),
        ),
    ]
