# Generated by Django 4.0.6 on 2022-07-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Infograins', '0022_rename_product_img_product_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_logo_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='media'),
        ),
    ]
