# Generated by Django 4.0.6 on 2022-07-13 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Infograins', '0023_product_product_logo_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=80)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='media')),
                ('description', models.TextField(verbose_name='')),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='Technology',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='Infograins.technology'),
        ),
    ]
