# Generated by Django 4.0.6 on 2022-07-13 09:32

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Infograins', '0024_technology_product_technology'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='conten',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
        ),
    ]
